<?php


namespace app\controller;


class Shopgoods extends Resource
{

    public function index()
    {
        $list = parent::index(); // TODO: Change the autogenerated stub
        print_r(123);
        return $list;
    }
}