<?php


namespace app\controller;


use app\lib\Res;
use think\Db;

class ShopGoods extends Resource
{

    public function index()
    {
        //$list = parent::index(); // TODO: Change the autogenerated stub
        return new Res('index');
        //return $list;
    }

    public function read()
    {
        //$list = parent::index(); // TODO: Change the autogenerated stub
        return new Res('read');
        //return $list;
    }

    public function ss()
    {
        //$list = parent::index(); // TODO: Change the autogenerated stub
        return new Res('ss');
        //return $list;
    }
}